# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_EspRFTool.ui'
#
# Created: Wed Nov 15 15:00:15 2017
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class myComboBox(QtGui.QComboBox):
    clicked = QtCore.pyqtSignal()
    def mousePressEvent(self, event):
        """ QComboBox.mousePressEvent(QMouseEvent) """
        if event.button() == QtCore.Qt.LeftButton:
            self.clicked.emit()

class Ui_EspRFtestTool(object):
    def setupUi(self, EspRFtestTool):
        EspRFtestTool.setObjectName(_fromUtf8("EspRFtestTool"))
        EspRFtestTool.resize(550, 550)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(EspRFtestTool.sizePolicy().hasHeightForWidth())
        EspRFtestTool.setSizePolicy(sizePolicy)
        EspRFtestTool.setMinimumSize(QtCore.QSize(550, 550))
        EspRFtestTool.setMaximumSize(QtCore.QSize(550, 550))
        self.tbSerial = QtGui.QTextBrowser(EspRFtestTool)
        self.tbSerial.setGeometry(QtCore.QRect(10, 300, 531, 241))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(200)
        sizePolicy.setHeightForWidth(self.tbSerial.sizePolicy().hasHeightForWidth())
        self.tbSerial.setSizePolicy(sizePolicy)
        self.tbSerial.setObjectName(_fromUtf8("tbSerial"))
        self.line = QtGui.QFrame(EspRFtestTool)
        self.line.setGeometry(QtCore.QRect(-3, 30, 611, 20))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.line_2 = QtGui.QFrame(EspRFtestTool)
        self.line_2.setGeometry(QtCore.QRect(0, 70, 911, 20))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayoutWidget = QtGui.QWidget(EspRFtestTool)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 40, 551, 41))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setContentsMargins(5, -1, 5, -1)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.pbLoadBin = QtGui.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbLoadBin.sizePolicy().hasHeightForWidth())
        self.pbLoadBin.setSizePolicy(sizePolicy)
        self.pbLoadBin.setObjectName(_fromUtf8("pbLoadBin"))
        self.horizontalLayout_5.addWidget(self.pbLoadBin)
        self.pbOpenFile = QtGui.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbOpenFile.sizePolicy().hasHeightForWidth())
        self.pbOpenFile.setSizePolicy(sizePolicy)
        self.pbOpenFile.setObjectName(_fromUtf8("pbOpenFile"))
        self.horizontalLayout_5.addWidget(self.pbOpenFile)
        self.leFilePath = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.leFilePath.setEnabled(False)
        self.leFilePath.setObjectName(_fromUtf8("leFilePath"))
        self.horizontalLayout_5.addWidget(self.leFilePath)
        self.prbLoad = QtGui.QProgressBar(self.verticalLayoutWidget)
        self.prbLoad.setProperty("value", 0)
        self.prbLoad.setObjectName(_fromUtf8("prbLoad"))
        self.horizontalLayout_5.addWidget(self.prbLoad)
        self.verticalLayout_11.addLayout(self.horizontalLayout_5)
        self.horizontalLayoutWidget = QtGui.QWidget(EspRFtestTool)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 551, 41))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout_1 = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_1.setContentsMargins(5, -1, 5, -1)
        self.horizontalLayout_1.setObjectName(_fromUtf8("horizontalLayout_1"))
        self.label_2 = QtGui.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_1.addWidget(self.label_2)
        self.cbChipType = QtGui.QComboBox(self.horizontalLayoutWidget)
        self.cbChipType.setObjectName(_fromUtf8("cbChipType"))
        self.cbChipType.addItem(_fromUtf8(""))
        self.cbChipType.addItem(_fromUtf8(""))
        self.horizontalLayout_1.addWidget(self.cbChipType)
        self.label_3 = QtGui.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_1.addWidget(self.label_3)
        self.cbComIndex = myComboBox(self.horizontalLayoutWidget)
        self.cbComIndex.setObjectName(_fromUtf8("cbComIndex"))
        self.cbComIndex.addItem(_fromUtf8(""))
        self.horizontalLayout_1.addWidget(self.cbComIndex)
        self.label = QtGui.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_1.addWidget(self.label)
        self.cbComBaud = QtGui.QComboBox(self.horizontalLayoutWidget)
        self.cbComBaud.setObjectName(_fromUtf8("cbComBaud"))
        self.cbComBaud.addItem(_fromUtf8(""))
        self.cbComBaud.addItem(_fromUtf8(""))
        self.cbComBaud.addItem(_fromUtf8(""))
        self.cbComBaud.addItem(_fromUtf8(""))
        self.cbComBaud.addItem(_fromUtf8(""))
        self.horizontalLayout_1.addWidget(self.cbComBaud)
        self.pbOpenSerial = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.pbOpenSerial.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pbOpenSerial.sizePolicy().hasHeightForWidth())
        self.pbOpenSerial.setSizePolicy(sizePolicy)
        self.pbOpenSerial.setObjectName(_fromUtf8("pbOpenSerial"))
        self.horizontalLayout_1.addWidget(self.pbOpenSerial)
        self.twTestPanel = QtGui.QTabWidget(EspRFtestTool)
        self.twTestPanel.setEnabled(True)
        self.twTestPanel.setGeometry(QtCore.QRect(10, 90, 533, 201))
        self.twTestPanel.setObjectName(_fromUtf8("twTestPanel"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.cbWFTestMode = QtGui.QComboBox(self.tab)
        self.cbWFTestMode.setGeometry(QtCore.QRect(20, 40, 101, 22))
        self.cbWFTestMode.setObjectName(_fromUtf8("cbWFTestMode"))
        self.cbWFTestMode.addItem(_fromUtf8(""))
        self.cbWFTestMode.addItem(_fromUtf8(""))
        self.cbWFTestMode.addItem(_fromUtf8(""))
        self.cbWFTestMode.addItem(_fromUtf8(""))
        self.label_4 = QtGui.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(20, 20, 101, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(20, 70, 101, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.leWFAtten = QtGui.QLineEdit(self.tab)
        self.leWFAtten.setGeometry(QtCore.QRect(20, 90, 101, 20))
        self.leWFAtten.setObjectName(_fromUtf8("leWFAtten"))
        self.cbWFDataRate = QtGui.QComboBox(self.tab)
        self.cbWFDataRate.setGeometry(QtCore.QRect(410, 40, 101, 22))
        self.cbWFDataRate.setObjectName(_fromUtf8("cbWFDataRate"))
        self.cbWFDataRate.addItem(_fromUtf8(""))
        self.cbWFDataRate.addItem(_fromUtf8(""))
        self.cbWFDataRate.addItem(_fromUtf8(""))
        self.cbWFDataRate.addItem(_fromUtf8(""))
        self.cbWFDataRate.addItem(_fromUtf8(""))
        self.cbWFDataRate.addItem(_fromUtf8(""))
        self.cbWFDataRate.addItem(_fromUtf8(""))
        self.cbWFDataRate.addItem(_fromUtf8(""))
        self.cbWFDataRate.addItem(_fromUtf8(""))
        self.cbWFDataRate.addItem(_fromUtf8(""))
        self.cbWFDataRate.addItem(_fromUtf8(""))
        self.cbWFDataRate.addItem(_fromUtf8(""))
        self.cbWFDataRate.addItem(_fromUtf8(""))
        self.cbWFDataRate.addItem(_fromUtf8(""))
        self.cbWFDataRate.addItem(_fromUtf8(""))
        self.cbWFDataRate.addItem(_fromUtf8(""))
        self.cbWFDataRate.addItem(_fromUtf8(""))
        self.cbWFDataRate.addItem(_fromUtf8(""))
        self.cbWFDataRate.addItem(_fromUtf8(""))
        self.cbWFDataRate.addItem(_fromUtf8(""))
        self.label_6 = QtGui.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(410, 20, 101, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.cbWFChannel = QtGui.QComboBox(self.tab)
        self.cbWFChannel.setGeometry(QtCore.QRect(150, 40, 101, 22))
        self.cbWFChannel.setObjectName(_fromUtf8("cbWFChannel"))
        self.cbWFChannel.addItem(_fromUtf8(""))
        self.cbWFChannel.addItem(_fromUtf8(""))
        self.cbWFChannel.addItem(_fromUtf8(""))
        self.cbWFChannel.addItem(_fromUtf8(""))
        self.cbWFChannel.addItem(_fromUtf8(""))
        self.cbWFChannel.addItem(_fromUtf8(""))
        self.cbWFChannel.addItem(_fromUtf8(""))
        self.cbWFChannel.addItem(_fromUtf8(""))
        self.cbWFChannel.addItem(_fromUtf8(""))
        self.cbWFChannel.addItem(_fromUtf8(""))
        self.cbWFChannel.addItem(_fromUtf8(""))
        self.cbWFChannel.addItem(_fromUtf8(""))
        self.cbWFChannel.addItem(_fromUtf8(""))
        self.cbWFChannel.addItem(_fromUtf8(""))
        self.label_7 = QtGui.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(150, 20, 101, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(280, 20, 101, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.cbWFBandWidth = QtGui.QComboBox(self.tab)
        self.cbWFBandWidth.setGeometry(QtCore.QRect(280, 40, 101, 22))
        self.cbWFBandWidth.setObjectName(_fromUtf8("cbWFBandWidth"))
        self.cbWFBandWidth.addItem(_fromUtf8(""))
        self.cbWFBandWidth.addItem(_fromUtf8(""))
        self.pbWFStop = QtGui.QPushButton(self.tab)
        self.pbWFStop.setGeometry(QtCore.QRect(440, 140, 71, 23))
        self.pbWFStop.setObjectName(_fromUtf8("pbWFStop"))
        self.pbWFSend = QtGui.QPushButton(self.tab)
        self.pbWFSend.setGeometry(QtCore.QRect(360, 140, 71, 23))
        self.pbWFSend.setObjectName(_fromUtf8("pbWFSend"))
        self.twTestPanel.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.cbBTTestMode = QtGui.QComboBox(self.tab_2)
        self.cbBTTestMode.setGeometry(QtCore.QRect(20, 40, 101, 22))
        self.cbBTTestMode.setObjectName(_fromUtf8("cbBTTestMode"))
        self.cbBTTestMode.addItem(_fromUtf8(""))
        self.cbBTTestMode.addItem(_fromUtf8(""))
        self.cbBTTestMode.addItem(_fromUtf8(""))
        self.cbBTTestMode.addItem(_fromUtf8(""))
        self.cbBTTestMode.addItem(_fromUtf8(""))
        self.pbBTStop = QtGui.QPushButton(self.tab_2)
        self.pbBTStop.setGeometry(QtCore.QRect(440, 140, 71, 23))
        self.pbBTStop.setObjectName(_fromUtf8("pbBTStop"))
        self.cbBTChannel = QtGui.QComboBox(self.tab_2)
        self.cbBTChannel.setGeometry(QtCore.QRect(280, 40, 101, 22))
        self.cbBTChannel.setObjectName(_fromUtf8("cbBTChannel"))
        self.label_9 = QtGui.QLabel(self.tab_2)
        self.label_9.setGeometry(QtCore.QRect(280, 20, 101, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.lbBTPowerLevel = QtGui.QLabel(self.tab_2)
        self.lbBTPowerLevel.setGeometry(QtCore.QRect(150, 20, 101, 16))
        self.lbBTPowerLevel.setObjectName(_fromUtf8("lbBTPowerLevel"))
        self.label_11 = QtGui.QLabel(self.tab_2)
        self.label_11.setGeometry(QtCore.QRect(20, 20, 101, 16))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtGui.QLabel(self.tab_2)
        self.label_12.setGeometry(QtCore.QRect(20, 120, 101, 16))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.cbBTChanJmp = QtGui.QComboBox(self.tab_2)
        self.cbBTChanJmp.setGeometry(QtCore.QRect(20, 140, 101, 22))
        self.cbBTChanJmp.setObjectName(_fromUtf8("cbBTChanJmp"))
        self.cbBTChanJmp.addItem(_fromUtf8(""))
        self.cbBTChanJmp.addItem(_fromUtf8(""))
        self.cbBTDataRate = QtGui.QComboBox(self.tab_2)
        self.cbBTDataRate.setGeometry(QtCore.QRect(150, 90, 101, 22))
        self.cbBTDataRate.setObjectName(_fromUtf8("cbBTDataRate"))
        self.label_13 = QtGui.QLabel(self.tab_2)
        self.label_13.setGeometry(QtCore.QRect(150, 70, 101, 16))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.cbBTPowerLevel = QtGui.QComboBox(self.tab_2)
        self.cbBTPowerLevel.setGeometry(QtCore.QRect(150, 40, 101, 22))
        self.cbBTPowerLevel.setObjectName(_fromUtf8("cbBTPowerLevel"))
        self.cbBTPowerLevel.addItem(_fromUtf8(""))
        self.cbBTPowerLevel.addItem(_fromUtf8(""))
        self.cbBTPowerLevel.addItem(_fromUtf8(""))
        self.cbBTPowerLevel.addItem(_fromUtf8(""))
        self.cbBTPowerLevel.addItem(_fromUtf8(""))
        self.cbBTPowerLevel.addItem(_fromUtf8(""))
        self.cbBTPowerLevel.addItem(_fromUtf8(""))
        self.cbBTPowerLevel.addItem(_fromUtf8(""))
        self.cbBTPowerLevel.addItem(_fromUtf8(""))
        self.cbBTDataType = QtGui.QComboBox(self.tab_2)
        self.cbBTDataType.setGeometry(QtCore.QRect(20, 90, 101, 22))
        self.cbBTDataType.setObjectName(_fromUtf8("cbBTDataType"))
        self.cbBTDataType.addItem(_fromUtf8(""))
        self.cbBTDataType.addItem(_fromUtf8(""))
        self.cbBTDataType.addItem(_fromUtf8(""))
        self.label_14 = QtGui.QLabel(self.tab_2)
        self.label_14.setGeometry(QtCore.QRect(20, 70, 101, 16))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_15 = QtGui.QLabel(self.tab_2)
        self.label_15.setGeometry(QtCore.QRect(280, 70, 101, 16))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.cbBTDHType = QtGui.QComboBox(self.tab_2)
        self.cbBTDHType.setGeometry(QtCore.QRect(280, 90, 101, 22))
        self.cbBTDHType.setObjectName(_fromUtf8("cbBTDHType"))
        self.cbBTDHType.addItem(_fromUtf8(""))
        self.cbBTDHType.addItem(_fromUtf8(""))
        self.cbBTDHType.addItem(_fromUtf8(""))
        self.label_16 = QtGui.QLabel(self.tab_2)
        self.label_16.setGeometry(QtCore.QRect(410, 20, 101, 16))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.leBTPayload = QtGui.QLineEdit(self.tab_2)
        self.leBTPayload.setGeometry(QtCore.QRect(410, 40, 101, 20))
        self.leBTPayload.setObjectName(_fromUtf8("leBTPayload"))
        self.label_17 = QtGui.QLabel(self.tab_2)
        self.label_17.setGeometry(QtCore.QRect(410, 70, 101, 16))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.cbBTSyncw = QtGui.QComboBox(self.tab_2)
        self.cbBTSyncw.setGeometry(QtCore.QRect(410, 90, 101, 22))
        self.cbBTSyncw.setObjectName(_fromUtf8("cbBTSyncw"))
        self.cbBTSyncw.addItem(_fromUtf8(""))
        self.cbBTSyncw.addItem(_fromUtf8(""))
        self.leSyncw = QtGui.QLineEdit(self.tab_2)
        self.leSyncw.setGeometry(QtCore.QRect(410, 90, 82, 22))
        self.leSyncw.setObjectName(_fromUtf8("leSyncw"))
        self.pbBTSend = QtGui.QPushButton(self.tab_2)
        self.pbBTSend.setGeometry(QtCore.QRect(360, 140, 71, 23))
        self.pbBTSend.setObjectName(_fromUtf8("pbBTSend"))
        self.twTestPanel.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.gbSend = QtGui.QGroupBox(self.tab_3)
        self.gbSend.setEnabled(True)
        self.gbSend.setGeometry(QtCore.QRect(0, 0, 531, 181))
        self.gbSend.setTitle(_fromUtf8(""))
        self.gbSend.setObjectName(_fromUtf8("gbSend"))
        self.rbSend1 = QtGui.QRadioButton(self.gbSend)
        self.rbSend1.setGeometry(QtCore.QRect(10, 10, 16, 16))
        self.rbSend1.setText(_fromUtf8(""))
        self.rbSend1.setObjectName(_fromUtf8("rbSend1"))
        self.rbSend2 = QtGui.QRadioButton(self.gbSend)
        self.rbSend2.setGeometry(QtCore.QRect(10, 30, 16, 16))
        self.rbSend2.setText(_fromUtf8(""))
        self.rbSend2.setObjectName(_fromUtf8("rbSend2"))
        self.rbSend3 = QtGui.QRadioButton(self.gbSend)
        self.rbSend3.setGeometry(QtCore.QRect(10, 50, 16, 16))
        self.rbSend3.setText(_fromUtf8(""))
        self.rbSend3.setObjectName(_fromUtf8("rbSend3"))
        self.rbSend4 = QtGui.QRadioButton(self.gbSend)
        self.rbSend4.setGeometry(QtCore.QRect(10, 70, 16, 16))
        self.rbSend4.setText(_fromUtf8(""))
        self.rbSend4.setObjectName(_fromUtf8("rbSend4"))
        self.rbSend5 = QtGui.QRadioButton(self.gbSend)
        self.rbSend5.setGeometry(QtCore.QRect(10, 90, 16, 16))
        self.rbSend5.setText(_fromUtf8(""))
        self.rbSend5.setObjectName(_fromUtf8("rbSend5"))
        self.rbSend6 = QtGui.QRadioButton(self.gbSend)
        self.rbSend6.setGeometry(QtCore.QRect(10, 110, 16, 16))
        self.rbSend6.setText(_fromUtf8(""))
        self.rbSend6.setObjectName(_fromUtf8("rbSend6"))
        self.rbSend7 = QtGui.QRadioButton(self.gbSend)
        self.rbSend7.setGeometry(QtCore.QRect(10, 130, 16, 16))
        self.rbSend7.setText(_fromUtf8(""))
        self.rbSend7.setObjectName(_fromUtf8("rbSend7"))
        self.rbSend8 = QtGui.QRadioButton(self.gbSend)
        self.rbSend8.setGeometry(QtCore.QRect(10, 150, 16, 16))
        self.rbSend8.setText(_fromUtf8(""))
        self.rbSend8.setObjectName(_fromUtf8("rbSend8"))
        self.leSend1 = QtGui.QLineEdit(self.gbSend)
        self.leSend1.setGeometry(QtCore.QRect(30, 10, 191, 20))
        self.leSend1.setObjectName(_fromUtf8("leSend1"))
        self.leSend2 = QtGui.QLineEdit(self.gbSend)
        self.leSend2.setGeometry(QtCore.QRect(30, 30, 191, 20))
        self.leSend2.setObjectName(_fromUtf8("leSend2"))
        self.leSend3 = QtGui.QLineEdit(self.gbSend)
        self.leSend3.setGeometry(QtCore.QRect(30, 50, 191, 20))
        self.leSend3.setObjectName(_fromUtf8("leSend3"))
        self.leSend4 = QtGui.QLineEdit(self.gbSend)
        self.leSend4.setGeometry(QtCore.QRect(30, 70, 191, 20))
        self.leSend4.setObjectName(_fromUtf8("leSend4"))
        self.leSend7 = QtGui.QLineEdit(self.gbSend)
        self.leSend7.setGeometry(QtCore.QRect(30, 130, 191, 20))
        self.leSend7.setObjectName(_fromUtf8("leSend7"))
        self.leSend8 = QtGui.QLineEdit(self.gbSend)
        self.leSend8.setGeometry(QtCore.QRect(30, 150, 191, 20))
        self.leSend8.setObjectName(_fromUtf8("leSend8"))
        self.leSend6 = QtGui.QLineEdit(self.gbSend)
        self.leSend6.setGeometry(QtCore.QRect(30, 110, 191, 20))
        self.leSend6.setObjectName(_fromUtf8("leSend6"))
        self.leSend5 = QtGui.QLineEdit(self.gbSend)
        self.leSend5.setGeometry(QtCore.QRect(30, 90, 191, 20))
        self.leSend5.setObjectName(_fromUtf8("leSend5"))
        self.rbSend9 = QtGui.QRadioButton(self.gbSend)
        self.rbSend9.setGeometry(QtCore.QRect(240, 10, 16, 16))
        self.rbSend9.setText(_fromUtf8(""))
        self.rbSend9.setObjectName(_fromUtf8("rbSend9"))
        self.leSend14 = QtGui.QLineEdit(self.gbSend)
        self.leSend14.setGeometry(QtCore.QRect(260, 110, 191, 20))
        self.leSend14.setObjectName(_fromUtf8("leSend14"))
        self.rbSend15 = QtGui.QRadioButton(self.gbSend)
        self.rbSend15.setGeometry(QtCore.QRect(240, 130, 16, 16))
        self.rbSend15.setText(_fromUtf8(""))
        self.rbSend15.setObjectName(_fromUtf8("rbSend15"))
        self.leSend15 = QtGui.QLineEdit(self.gbSend)
        self.leSend15.setGeometry(QtCore.QRect(260, 130, 191, 20))
        self.leSend15.setObjectName(_fromUtf8("leSend15"))
        self.rbSend12 = QtGui.QRadioButton(self.gbSend)
        self.rbSend12.setGeometry(QtCore.QRect(240, 70, 16, 16))
        self.rbSend12.setText(_fromUtf8(""))
        self.rbSend12.setObjectName(_fromUtf8("rbSend12"))
        self.leSend11 = QtGui.QLineEdit(self.gbSend)
        self.leSend11.setGeometry(QtCore.QRect(260, 50, 191, 20))
        self.leSend11.setObjectName(_fromUtf8("leSend11"))
        self.leSend12 = QtGui.QLineEdit(self.gbSend)
        self.leSend12.setGeometry(QtCore.QRect(260, 70, 191, 20))
        self.leSend12.setObjectName(_fromUtf8("leSend12"))
        self.leSend13 = QtGui.QLineEdit(self.gbSend)
        self.leSend13.setGeometry(QtCore.QRect(260, 90, 191, 20))
        self.leSend13.setObjectName(_fromUtf8("leSend13"))
        self.rbSend13 = QtGui.QRadioButton(self.gbSend)
        self.rbSend13.setGeometry(QtCore.QRect(240, 90, 16, 16))
        self.rbSend13.setText(_fromUtf8(""))
        self.rbSend13.setObjectName(_fromUtf8("rbSend13"))
        self.leSend9 = QtGui.QLineEdit(self.gbSend)
        self.leSend9.setGeometry(QtCore.QRect(260, 10, 191, 20))
        self.leSend9.setObjectName(_fromUtf8("leSend9"))
        self.leSend10 = QtGui.QLineEdit(self.gbSend)
        self.leSend10.setGeometry(QtCore.QRect(260, 30, 191, 20))
        self.leSend10.setObjectName(_fromUtf8("leSend10"))
        self.rbSend11 = QtGui.QRadioButton(self.gbSend)
        self.rbSend11.setGeometry(QtCore.QRect(240, 50, 16, 16))
        self.rbSend11.setText(_fromUtf8(""))
        self.rbSend11.setObjectName(_fromUtf8("rbSend11"))
        self.rbSend10 = QtGui.QRadioButton(self.gbSend)
        self.rbSend10.setGeometry(QtCore.QRect(240, 30, 16, 16))
        self.rbSend10.setText(_fromUtf8(""))
        self.rbSend10.setObjectName(_fromUtf8("rbSend10"))
        self.leSend16 = QtGui.QLineEdit(self.gbSend)
        self.leSend16.setGeometry(QtCore.QRect(260, 150, 191, 20))
        self.leSend16.setObjectName(_fromUtf8("leSend16"))
        self.rbSend16 = QtGui.QRadioButton(self.gbSend)
        self.rbSend16.setGeometry(QtCore.QRect(240, 150, 16, 16))
        self.rbSend16.setText(_fromUtf8(""))
        self.rbSend16.setObjectName(_fromUtf8("rbSend16"))
        self.rbSend14 = QtGui.QRadioButton(self.gbSend)
        self.rbSend14.setGeometry(QtCore.QRect(240, 110, 16, 16))
        self.rbSend14.setText(_fromUtf8(""))
        self.rbSend14.setObjectName(_fromUtf8("rbSend14"))
        self.pbSend = QtGui.QPushButton(self.gbSend)
        self.pbSend.setGeometry(QtCore.QRect(460, 150, 61, 23))
        self.pbSend.setObjectName(_fromUtf8("pbSend"))
        self.twTestPanel.addTab(self.tab_3, _fromUtf8(""))
        self.leCOM = QtGui.QLineEdit(EspRFtestTool)
        self.leCOM.setGeometry(QtCore.QRect(370, 10, 76, 20))
        self.leCOM.setObjectName(_fromUtf8("leCOM"))

        self.retranslateUi(EspRFtestTool)
        self.twTestPanel.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(EspRFtestTool)

    def retranslateUi(self, EspRFtestTool):
        EspRFtestTool.setWindowTitle(_translate("EspRFtestTool", "EspRFtestTool", None))
        self.pbLoadBin.setText(_translate("EspRFtestTool", "加载测试bin", None))
        self.pbOpenFile.setText(_translate("EspRFtestTool", "选择测试bin", None))
        self.label_2.setText(_translate("EspRFtestTool", "芯片平台", None))
        self.cbChipType.setItemText(0, _translate("EspRFtestTool", "ESP8266", None))
        self.cbChipType.setItemText(1, _translate("EspRFtestTool", "ESP32", None))
        self.label_3.setText(_translate("EspRFtestTool", "串口选择", None))
        self.cbComIndex.setItemText(0, _translate("EspRFtestTool", "--", None))
        self.label.setText(_translate("EspRFtestTool", " 波特率 ", None))
        self.cbComBaud.setItemText(0, _translate("EspRFtestTool", "9600", None))
        self.cbComBaud.setItemText(1, _translate("EspRFtestTool", "74880", None))
        self.cbComBaud.setItemText(2, _translate("EspRFtestTool", "115200", None))
        self.cbComBaud.setItemText(3, _translate("EspRFtestTool", "921600", None))
        self.cbComBaud.setItemText(4, _translate("EspRFtestTool", "custom", None))
        self.pbOpenSerial.setText(_translate("EspRFtestTool", "打开串口", None))
        self.cbWFTestMode.setItemText(0, _translate("EspRFtestTool", "TX continues", None))
        self.cbWFTestMode.setItemText(1, _translate("EspRFtestTool", "TX packet", None))
        self.cbWFTestMode.setItemText(2, _translate("EspRFtestTool", "RX packet", None))
        self.cbWFTestMode.setItemText(3, _translate("EspRFtestTool", "TX tone", None))
        self.label_4.setText(_translate("EspRFtestTool", "测试模式：", None))
        self.label_5.setText(_translate("EspRFtestTool", "信号衰减(0.25dB)：", None))
        self.leWFAtten.setText(_translate("EspRFtestTool", "0", None))
        self.cbWFDataRate.setItemText(0, _translate("EspRFtestTool", "11b 1M", None))
        self.cbWFDataRate.setItemText(1, _translate("EspRFtestTool", "11b 2M", None))
        self.cbWFDataRate.setItemText(2, _translate("EspRFtestTool", "11b 5.5M", None))
        self.cbWFDataRate.setItemText(3, _translate("EspRFtestTool", "11b 11M", None))
        self.cbWFDataRate.setItemText(4, _translate("EspRFtestTool", "11g 6M", None))
        self.cbWFDataRate.setItemText(5, _translate("EspRFtestTool", "11g 9M", None))
        self.cbWFDataRate.setItemText(6, _translate("EspRFtestTool", "11g 12M", None))
        self.cbWFDataRate.setItemText(7, _translate("EspRFtestTool", "11g 18M", None))
        self.cbWFDataRate.setItemText(8, _translate("EspRFtestTool", "11g 24M", None))
        self.cbWFDataRate.setItemText(9, _translate("EspRFtestTool", "11g 36M", None))
        self.cbWFDataRate.setItemText(10, _translate("EspRFtestTool", "11g 48M", None))
        self.cbWFDataRate.setItemText(11, _translate("EspRFtestTool", "11g 54M", None))
        self.cbWFDataRate.setItemText(12, _translate("EspRFtestTool", "11n MCS0", None))
        self.cbWFDataRate.setItemText(13, _translate("EspRFtestTool", "11n MCS1", None))
        self.cbWFDataRate.setItemText(14, _translate("EspRFtestTool", "11n MCS2", None))
        self.cbWFDataRate.setItemText(15, _translate("EspRFtestTool", "11n MCS3", None))
        self.cbWFDataRate.setItemText(16, _translate("EspRFtestTool", "11n MCS4", None))
        self.cbWFDataRate.setItemText(17, _translate("EspRFtestTool", "11n MCS5", None))
        self.cbWFDataRate.setItemText(18, _translate("EspRFtestTool", "11n MCS6", None))
        self.cbWFDataRate.setItemText(19, _translate("EspRFtestTool", "11n MCS7", None))
        self.label_6.setText(_translate("EspRFtestTool", "WiFi速率：", None))
        self.cbWFChannel.setItemText(0, _translate("EspRFtestTool", "1/2412", None))
        self.cbWFChannel.setItemText(1, _translate("EspRFtestTool", "2/2417", None))
        self.cbWFChannel.setItemText(2, _translate("EspRFtestTool", "3/2422", None))
        self.cbWFChannel.setItemText(3, _translate("EspRFtestTool", "4/2427", None))
        self.cbWFChannel.setItemText(4, _translate("EspRFtestTool", "5/2432", None))
        self.cbWFChannel.setItemText(5, _translate("EspRFtestTool", "6/2437", None))
        self.cbWFChannel.setItemText(6, _translate("EspRFtestTool", "7/2442", None))
        self.cbWFChannel.setItemText(7, _translate("EspRFtestTool", "8/2447", None))
        self.cbWFChannel.setItemText(8, _translate("EspRFtestTool", "9/2452", None))
        self.cbWFChannel.setItemText(9, _translate("EspRFtestTool", "10/2457", None))
        self.cbWFChannel.setItemText(10, _translate("EspRFtestTool", "11/2462", None))
        self.cbWFChannel.setItemText(11, _translate("EspRFtestTool", "12/2467", None))
        self.cbWFChannel.setItemText(12, _translate("EspRFtestTool", "13/2472", None))
        self.cbWFChannel.setItemText(13, _translate("EspRFtestTool", "14/2484", None))
        self.label_7.setText(_translate("EspRFtestTool", "信道选择：", None))
        self.label_8.setText(_translate("EspRFtestTool", "信道带宽：", None))
        self.cbWFBandWidth.setItemText(0, _translate("EspRFtestTool", "20M", None))
        self.cbWFBandWidth.setItemText(1, _translate("EspRFtestTool", "40M", None))
        self.pbWFStop.setText(_translate("EspRFtestTool", "stop", None))
        self.pbWFSend.setText(_translate("EspRFtestTool", "start", None))
        self.twTestPanel.setTabText(self.twTestPanel.indexOf(self.tab), _translate("EspRFtestTool", "wifi测试", None))
        self.cbBTTestMode.setItemText(0, _translate("EspRFtestTool", "classBT TX", None))
        self.cbBTTestMode.setItemText(1, _translate("EspRFtestTool", "classBT RX/BR", None))
        self.cbBTTestMode.setItemText(1, _translate("EspRFtestTool", "classBT RX/EDR", None))
        self.cbBTTestMode.setItemText(2, _translate("EspRFtestTool", "BLE TX", None))
        self.cbBTTestMode.setItemText(2, _translate("EspRFtestTool", "BLE TX Syncw", None))
        self.cbBTTestMode.setItemText(3, _translate("EspRFtestTool", "BLE RX", None))
        self.cbBTTestMode.setItemText(4, _translate("EspRFtestTool", "BT TX tone", None))
        self.pbBTStop.setText(_translate("EspRFtestTool", "stop", None))
        self.label_9.setText(_translate("EspRFtestTool", "信道选择：", None))
        self.lbBTPowerLevel.setText(_translate("EspRFtestTool", "功耗等级(dB)：", None))
        self.label_11.setText(_translate("EspRFtestTool", "蓝牙测试模式：", None))
        self.label_12.setText(_translate("EspRFtestTool", "是否跳频：", None))
        self.cbBTChanJmp.setItemText(0, _translate("EspRFtestTool", "No", None))
        self.cbBTChanJmp.setItemText(1, _translate("EspRFtestTool", "Yes", None))
        self.label_13.setText(_translate("EspRFtestTool", "调制方式：", None))
        self.cbBTPowerLevel.setItemText(0, _translate("EspRFtestTool", "0", None))
        self.cbBTPowerLevel.setItemText(1, _translate("EspRFtestTool", "1", None))
        self.cbBTPowerLevel.setItemText(2, _translate("EspRFtestTool", "2", None))
        self.cbBTPowerLevel.setItemText(3, _translate("EspRFtestTool", "3", None))
        self.cbBTPowerLevel.setItemText(4, _translate("EspRFtestTool", "4", None))
        self.cbBTPowerLevel.setItemText(5, _translate("EspRFtestTool", "5", None))
        self.cbBTPowerLevel.setItemText(6, _translate("EspRFtestTool", "6", None))
        self.cbBTPowerLevel.setItemText(7, _translate("EspRFtestTool", "7", None))
        self.cbBTPowerLevel.setItemText(8, _translate("EspRFtestTool", "8", None))
        self.cbBTDataType.setItemText(0, _translate("EspRFtestTool", "1010", None))
        self.cbBTDataType.setItemText(1, _translate("EspRFtestTool", "00001111", None))
        self.cbBTDataType.setItemText(2, _translate("EspRFtestTool", "prbs9", None))
        self.label_14.setText(_translate("EspRFtestTool", "Data类型：", None))
        self.label_15.setText(_translate("EspRFtestTool", "DH类型：", None))
        self.cbBTDHType.setItemText(0, _translate("EspRFtestTool", "DH1", None))
        self.cbBTDHType.setItemText(1, _translate("EspRFtestTool", "DH3", None))
        self.cbBTDHType.setItemText(2, _translate("EspRFtestTool", "DH5", None))
        self.label_16.setText(_translate("EspRFtestTool", "负载长度(0~255)：", None))
        self.leBTPayload.setText(_translate("EspRFtestTool", "0", None))
        self.label_17.setText(_translate("EspRFtestTool", "包的身份识别：", None))
        self.cbBTSyncw.setItemText(0, _translate("EspRFtestTool", "0x71764129", None))
        self.cbBTSyncw.setItemText(1, _translate("EspRFtestTool", "custom", None))
        self.pbBTSend.setText(_translate("EspRFtestTool", "start", None))
        self.twTestPanel.setTabText(self.twTestPanel.indexOf(self.tab_2), _translate("EspRFtestTool", "BT测试 ", None))
        self.pbSend.setText(_translate("EspRFtestTool", "send", None))
        self.twTestPanel.setTabText(self.twTestPanel.indexOf(self.tab_3), _translate("EspRFtestTool", "手动测试", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    EspRFtestTool = QtGui.QWidget()
    ui = Ui_EspRFtestTool()
    ui.setupUi(EspRFtestTool)
    EspRFtestTool.show()
    sys.exit(app.exec_())

